[package]
name = "vesper-provider-synthetic"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
futures-core.workspace = true
serde_json.workspace = true
vesper-domain = { path = "../vesper-domain", version = "=0.24.4" }
vesper-provider = { path = "../vesper-provider", version = "=0.24.4" }

[dev-dependencies]
futures-util.workspace = true
tokio = { workspace = true, features = ["macros", "rt"] }

[lints]
workspace = true
