//! Value types shared by the memory subsystem.
//!
//! These mirror the bounded shape of the Python oracle's
//! `awareness.EpistemicRecord` and `memory.*` data models, adapted to
//! Rust's type system and to Vesper's secret-safe confinement rules.

use std::time::SystemTime;

use serde::{Deserialize, Serialize};

use crate::error::MemoryError;

/// Maximum number of characters in a memory or awareness `summary`.
pub const MAX_SUMMARY_CHARS: usize = 1024;
/// Maximum number of scope tags on one record.
pub const MAX_SCOPES: usize = 8;
/// Maximum number of evidence references on one record.
pub const MAX_EVIDENCE: usize = 16;
/// Hard cap on the number of memory entries the store will accept.
pub const MAX_ENTRIES: usize = 10_000;
/// Maximum number of characters in a record id.
pub const MAX_ID_CHARS: usize = 64;
/// Maximum number of chunks declared by one skill manifest (context-paging
/// tier; ADR 0024 orchestrator + advanced-context-paging PRD D1). 32 is
/// 3.5x the largest section count observed across the 326-file seed
/// library, with headroom for reference skills that split per topic.
pub const MAX_CHUNKS_PER_SKILL: usize = 32;
/// Maximum allowed size of one chunk file in bytes. Matches
/// `MAX_SKILL_CONTEXT_CHARS`: a chunk larger than one skill's full
/// inline-injection budget could never be consumed whole, so it is
/// rejected at validation time instead of being silently truncated.
pub const MAX_CHUNK_BYTES: usize = 24_000;
/// Maximum characters in one chunk-manifest `description` (required field).
pub const MAX_CHUNK_DESCRIPTION_CHARS: usize = 240;
/// Maximum characters in one chunk-manifest `summary` (optional field).
pub const MAX_CHUNK_SUMMARY_CHARS: usize = 480;
/// Maximum `key_elements` entries per chunk manifest entry (optional field).
pub const MAX_CHUNK_KEY_ELEMENTS: usize = 8;

/// Kind tag for a memory entry. The full surface mirrors the 13 Tier C
/// Phase 8 commands (`/memory`, `/goal`, `/subgoal`, `/skills`,
/// `/profile`, `/awareness`, `/metacognition`, `/deliberation`,
/// `/repository`, `/meta-learning`, `/observability`, `/curator`,
/// `/journey`).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum MemoryKind {
    /// Free-form durable memory entry (the default `/memory` kind).
    Memory,
    /// Persistent goal (`/goal`).
    Goal,
    /// Acceptance criterion on the active goal (`/subgoal`).
    Subgoal,
    /// Learned skill descriptor (`/skills`).
    Skill,
    /// Cross-project user-profile preference (`/profile`).
    Profile,
    /// Epistemic observation (`/awareness`).
    Observation,
    /// Epistemic hypothesis (`/awareness`).
    Hypothesis,
    /// Epistemic assumption (`/awareness`).
    Assumption,
    /// Epistemic contradiction (`/awareness`).
    Contradiction,
    /// Epistemic unknown (`/awareness`).
    Unknown,
    /// Capability limit (`/awareness`).
    Capability,
    /// Metacognitive assessment (`/metacognition`).
    Metacognition,
    /// Grounded-deliberation hypothesis (`/deliberation`).
    Deliberation,
    /// Repository-intelligence observation (`/repository`).
    Repository,
    /// Meta-learning candidate (`/meta-learning`).
    MetaLearning,
    /// Local reliability-metric observation (`/observability`).
    Observability,
    /// Composite journey entry (`/journey`).
    Journey,
}

impl MemoryKind {
    /// Returns the lowercase kebab-case identifier used in the JSONL log.
    #[must_use]
    pub fn as_str(self) -> &'static str {
        match self {
            Self::Memory => "memory",
            Self::Goal => "goal",
            Self::Subgoal => "subgoal",
            Self::Skill => "skill",
            Self::Profile => "profile",
            Self::Observation => "observation",
            Self::Hypothesis => "hypothesis",
            Self::Assumption => "assumption",
            Self::Contradiction => "contradiction",
            Self::Unknown => "unknown",
            Self::Capability => "capability",
            Self::Metacognition => "metacognition",
            Self::Deliberation => "deliberation",
            Self::Repository => "repository",
            Self::MetaLearning => "meta-learning",
            Self::Observability => "observability",
            Self::Journey => "journey",
        }
    }
}

/// One durable memory entry. Serialized one-per-line in the JSONL log.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct MemoryEntry {
    /// Stable opaque identifier (caller-supplied or generated by the store).
    pub id: String,
    /// Kind tag.
    pub kind: MemoryKind,
    /// One-line summary (≤ [`MAX_SUMMARY_CHARS`] chars).
    pub summary: String,
    /// Optional scope tags (workspace-relative paths or feature names).
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub scopes: Vec<String>,
    /// Optional evidence references (harness-issued evidence IDs).
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub evidence: Vec<String>,
    /// Creation timestamp.
    pub created_at: SystemTime,
    /// Last-update timestamp.
    pub updated_at: SystemTime,
}

impl MemoryEntry {
    /// Validates the entry against the bounded contract. Returns the entry
    /// unchanged on success or [`MemoryError::BoundsViolated`] otherwise.
    pub fn validate(&self) -> Result<(), MemoryError> {
        if self.id.len() > MAX_ID_CHARS {
            return Err(MemoryError::BoundsViolated("id length"));
        }
        if self.summary.chars().count() > MAX_SUMMARY_CHARS {
            return Err(MemoryError::BoundsViolated("summary length"));
        }
        if self.scopes.len() > MAX_SCOPES {
            return Err(MemoryError::BoundsViolated("scope count"));
        }
        if self.evidence.len() > MAX_EVIDENCE {
            return Err(MemoryError::BoundsViolated("evidence count"));
        }
        Ok(())
    }
}

/// Confidence band for epistemic records (mirrors the oracle's
/// `awareness.CONFIDENCE_BANDS`).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum Confidence {
    Low,
    Medium,
    High,
}

/// Status of an epistemic record (mirrors the oracle's
/// `awareness.RECORD_STATUSES`).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum RecordStatus {
    Active,
    Resolved,
    Stale,
    Invalidated,
}

/// Bounded evidence event backing an epistemic record (mirrors
/// `awareness.EvidenceEvent`).
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct EvidenceEvent {
    /// Harness-issued evidence id (≤ 40 chars).
    pub id: String,
    /// Source class (`user`, `read`, `search`, `edit`, `diagnostic`,
    /// `verification`, `tool`).
    pub source: EvidenceSource,
    /// One-line summary (≤ [`MAX_SUMMARY_CHARS`] chars).
    pub summary: String,
}

/// Source class for evidence events.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum EvidenceSource {
    User,
    Read,
    Search,
    Edit,
    Diagnostic,
    Verification,
    Tool,
}

/// One bounded epistemic record (mirrors `awareness.EpistemicRecord`).
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct EpistemicRecord {
    pub id: String,
    pub kind: MemoryKind,
    pub summary: String,
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub scopes: Vec<String>,
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub evidence: Vec<EvidenceEvent>,
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub supports: Vec<String>,
    pub confidence: Confidence,
    pub status: RecordStatus,
    pub created_at: SystemTime,
    pub updated_at: SystemTime,
}

impl EpistemicRecord {
    /// Validates the record against the bounded contract.
    pub fn validate(&self) -> Result<(), MemoryError> {
        if self.id.len() > MAX_ID_CHARS {
            return Err(MemoryError::BoundsViolated("id length"));
        }
        if self.summary.chars().count() > MAX_SUMMARY_CHARS {
            return Err(MemoryError::BoundsViolated("summary length"));
        }
        if self.scopes.len() > MAX_SCOPES {
            return Err(MemoryError::BoundsViolated("scope count"));
        }
        if self.evidence.len() > MAX_EVIDENCE {
            return Err(MemoryError::BoundsViolated("evidence count"));
        }
        if self.supports.len() > MAX_SCOPES {
            return Err(MemoryError::BoundsViolated("supports count"));
        }
        Ok(())
    }
}

/// One declared on-demand chunk in a skill's `chunks:` frontmatter
/// manifest. The manifest is the always-loaded routing tier; chunk files
/// under `<skill resources>/chunks/<name>.md` are loaded only when routed
/// to (advanced-context-paging PRD D1/D2; schema shape from the context
/// upstream recon, MIT — no upstream code or text).
///
/// `summary` and `key_elements` are parsed from day one but do not
/// influence automatic routing until the PRD D3 eval gate records an
/// `ADOPT` verdict; they are carried for inspection and explicit routes.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SkillChunkManifestEntry {
    /// Chunk name; names the file `chunks/<name>.md`.
    pub name: String,
    /// Required one-line routing description.
    pub description: String,
    /// Optional denser summary for precision routing (D2; gated by D3).
    pub summary: Option<String>,
    /// Optional routing key terms (D2; gated by D3).
    pub key_elements: Option<Vec<String>>,
}

impl SkillChunkManifestEntry {
    /// Validates the entry against the bounded manifest contract.
    /// Returns [`MemoryError::BoundsViolated`] with a stable field name on
    /// any violation; nothing is silently truncated.
    pub fn validate(&self) -> Result<(), MemoryError> {
        if SkillSlug::new(&self.name).is_err() {
            return Err(MemoryError::InvalidIdentifier("chunk name".into()));
        }
        if self.description.chars().count() > MAX_CHUNK_DESCRIPTION_CHARS {
            return Err(MemoryError::BoundsViolated("chunk description length"));
        }
        if let Some(summary) = &self.summary
            && summary.chars().count() > MAX_CHUNK_SUMMARY_CHARS
        {
            return Err(MemoryError::BoundsViolated("chunk summary length"));
        }
        if let Some(elements) = &self.key_elements {
            if elements.len() > MAX_CHUNK_KEY_ELEMENTS {
                return Err(MemoryError::BoundsViolated("chunk key-elements count"));
            }
            if elements
                .iter()
                .any(|element| element.chars().count() > MAX_CHUNK_DESCRIPTION_CHARS)
            {
                return Err(MemoryError::BoundsViolated("chunk key-element length"));
            }
        }
        Ok(())
    }
}

/// A normalized identifier slug used for skill file names.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SkillSlug(String);

impl SkillSlug {
    /// Validates and constructs a slug. Lowercase ASCII letters, digits,
    /// and hyphens only; must start and end with a letter or digit; ≤ 64
    /// chars. Mirrors the oracle's `_ID` regex.
    pub fn new(raw: &str) -> Result<Self, MemoryError> {
        if raw.is_empty() || raw.len() > MAX_ID_CHARS {
            return Err(MemoryError::InvalidIdentifier("skill slug".into()));
        }
        let mut chars = raw.chars();
        let first = chars.next().expect("non-empty");
        if !first.is_ascii_lowercase() && !first.is_ascii_digit() {
            return Err(MemoryError::InvalidIdentifier("skill slug".into()));
        }
        if !raw
            .chars()
            .all(|c| c.is_ascii_lowercase() || c.is_ascii_digit() || c == '-')
        {
            return Err(MemoryError::InvalidIdentifier("skill slug".into()));
        }
        if raw.ends_with('-') {
            return Err(MemoryError::InvalidIdentifier("skill slug".into()));
        }
        Ok(Self(raw.to_string()))
    }

    /// Returns the slug as a string slice.
    #[must_use]
    pub fn as_str(&self) -> &str {
        &self.0
    }
}
